WITH NEWPC AS(SELECT ROW_NUMBER() OVER(ORDER BY code) AS no, code, price
FROM PC)

SELECT NPC.code, (SELECT AVG(price) FROM NEWPC WHERE no >= NPC.no AND no-5 <= NPC.no ) AS avgrpc
FROM NEWPC AS NPC
WHERE NPC.no + 4 < (SELECT COUNT(*) FROM PC)