WITH T AS (SELECT * 
FROM (SELECT 1 A1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS X1,
(SELECT 1 A2 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS X2,
(SELECT 1 A3 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10) AS X3)

SELECT class, REPLACE('bc-x', 'x', CAST(100*(A1-1) + 10*(A2-1) + A3 AS CHAR(4))) AS num
FROM T CROSS JOIN Classes
WHERE type = 'bc' AND (100*(A1-1) + 10*(A2-1) + A3 <= numGuns)