WITH My AS (SELECT ISNULL(B_Q_ID, Q_ID) AS ID, ISNULL(Q, 0) AS Q
FROM (SELECT B_Q_ID, (SUM(CASE WHEN C = 'R' THEN B_VOL ELSE 0 END) + 
SUM(CASE WHEN C = 'G' THEN B_VOL ELSE 0 END) +
SUM(CASE WHEN C = 'B' THEN B_VOL ELSE 0 END)) AS Q
FROM (SELECT *, (SELECT V_COLOR FROM utV WHERE V_ID = B_V_ID) AS C
FROM utB) AS T
GROUP BY B_Q_ID) AS T1 FULL JOIN utQ ON B_Q_ID = Q_ID)

SELECT (SELECT Q_NAME FROM utQ WHERE ID = Q_ID) AS Name, (SELECT COUNT(*) FROM My WHERE Q = 765) AS White, (SELECT COUNT(*) FROM My WHERE Q = 0) AS  Black
FROM My
WHERE Q = 0 OR Q = 765
