SELECT (SELECT Q_NAME FROM utQ WHERE T.B_Q_ID = Q_ID) AS Name, R
FROM (SELECT B_Q_ID,
SUM(CASE WHEN C = 'R' THEN B_VOL ELSE 0 END) AS R,
SUM(CASE WHEN C = 'G' THEN B_VOL ELSE 0 END) AS G,
SUM(CASE WHEN C = 'B' THEN B_VOL ELSE 0 END) AS B
FROM (SELECT *, (SELECT V_COLOR FROM utV WHERE V_ID = B_V_ID) AS C
FROM utB) AS T
GROUP BY B_Q_ID) AS T
WHERE R > 0 AND R < 255 AND R = G AND G = B AND B = R