SELECT date_begin, date_finish
FROM (SELECT ROW_NUMBER() OVER (ORDER BY date_begin) AS N, *
FROM (SELECT DISTINCT B_DATETIME AS date_begin
FROM utB
WHERE DATEADD(s, -1, B_DATETIME) NOT IN (SELECT B_DATETIME FROM utB) AND DATEADD(s, 1, B_DATETIME) IN (SELECT B_DATETIME FROM utB)) AS Start) AS T1 INNER JOIN (SELECT ROW_NUMBER() OVER (ORDER BY date_finish) AS N, *
FROM (SELECT DISTINCT B_DATETIME AS date_finish
FROM utB
WHERE DATEADD(s, 1, B_DATETIME) NOT IN (SELECT B_DATETIME FROM utB) AND DATEADD(s, -1, B_DATETIME) IN (SELECT B_DATETIME FROM utB)) AS Finish) AS T2 ON T1.N = T2.N