SELECT (SELECT Q_NAME FROM utQ WHERE Q_ID = Ras.Q_ID) AS Q_NAME
FROM (SELECT B_Q_ID AS Q_ID, SUM(CASE WHEN CR = 'R' THEN B_VOL ELSE 0 END) AS R, SUM(CASE WHEN CR = 'G' THEN B_VOL ELSE 0 END) AS G, SUM(CASE WHEN CR = 'B' THEN B_VOL ELSE 0 END) AS B
FROM (SELECT B_V_ID AS ID, (SELECT V_COLOR FROM utV WHERE P.B_V_ID = V_ID) AS CR
FROM (SELECT B_V_ID, SUM(B_VOL) AS C
FROM utB
GROUP BY B_V_ID) AS P
WHERE C = 255) AS Pusto INNER JOIN utB ON Pusto.ID = B_V_ID
GROUP BY B_Q_ID) AS Ras
WHERE R = 255 AND G = 255 AND B = 255