WITH NOTBLACK AS (SELECT 
(SELECT 255*COUNT(*) FROM utV WHERE V_COLOR = 'R') - SUM(CASE WHEN C = 'R' THEN B_VOL ELSE 0 END) AS R,
(SELECT 255*COUNT(*) FROM utV WHERE V_COLOR = 'G') - SUM(CASE WHEN C = 'G' THEN B_VOL ELSE 0 END) AS G,
(SELECT 255*COUNT(*) FROM utV WHERE V_COLOR = 'B') - SUM(CASE WHEN C = 'B' THEN B_VOL ELSE 0 END) AS B
FROM (SELECT *, (SELECT V_COLOR FROM utV WHERE V_ID = B_V_ID) AS C
FROM utB) AS T)

SELECT MIN(C) / 255 AS C
FROM (SELECT R AS C
FROM NOTBLACK
UNION ALL
SELECT G
FROM NOTBLACK
UNION ALL
SELECT B
FROM NOTBLACK) AS Y